name: deploy_to_firebase_hosting

on:
  push:
    tags:
      - release-production-*

jobs:
  deploy_to_firebase_hosting:

    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout the repository
        uses: actions/checkout@master
      
      - name: Deploy to Firebase
        uses: firebase deploy --token [1//0gSrrG9oljeoWCgYIARAAGBASNwF-L9Ir8-Aphe5hnT3w9dkevas2W4GPAIMJbxhV2WpYdpod9e01OF47n7p73DB_u_3XdlkHr8Y] --only hosting --non-interactive
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
